version: '3'
services:
  nano-server:
    build: ./nano-server
    ports:
    - "8080:8080"
    links:
    - redis
    depends_on:
      - "redis"
  nano-service:
    build: ./nano-service
    environment:
    - NANO_SERVICE_ADDRESS=nano-service
    - NANO_SERVER_ADDRESS=nano-server
    ports:
    - "8081:8081"
    links:
    - nano-server
    depends_on:
      - "nano-server"
  redis:
    image: redis
