name: Deployment

on: [push]

jobs:
  build:
    name: Build docker compose stack
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build the docker compose stack
      run: docker-compose -f tests/docker/docker-compose.yml up --detach

    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    - name: Check running containers
      run: docker ps

    - name: Post request to stack
      uses: swinton/httpie.action@master
      with:
        args: ["POST", "127.0.0.1:8080", "Pattern=role:math,cmd:sum, Left=1, Right=2"]