name: Deployment

on: [push]

jobs:
  build:
    name: Build docker compose stack
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build the docker compose stack
      run: docker-compose -f _tests/docker/docker-compose.yml up --detach

    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    - name: Check running containers
      run: docker ps
